# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

project_name: signoz-mcp-server

before:
  hooks:
    - go mod tidy

builds:
  - id: signoz
    binary: bin/signoz-mcp-server
    main: ./cmd/server/
    ldflags:
      - -s -w -X github.com/SigNoz/signoz-mcp-server/pkg/version.Version={{.Tag}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    goarm64:
      - v8.0
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{- .Os }}_{{- .Arch }}
    wrap_in_directory: true
    strip_binary_directory: false
    files:
      - src: README.md
        dst: README.md
      - src: LICENSE
        dst: LICENSE

release:
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto
